import streamlit as st
import os
import sys

# Add parent directory to path so we can import our modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from vector_rag.pipeline import VectorRAGPipeline
from graph_rag.retriever import GraphRAGRetriever
from utils.visualizer import create_radar_chart, load_metrics_from_csv
from config.settings import settings

st.set_page_config(
    page_title="RAG Comparison: Vector vs Graph",
    page_icon="🔍",
    layout="wide"
)

st.title("🔍 RAG Architecture Comparison")
st.markdown("""
This application compares two different Retrieval-Augmented Generation (RAG) approaches on the same dataset (ISO 20022 Payments Guide).
- **Vector RAG**: Uses FAISS vector embeddings and similarity search.
- **Graph RAG**: Uses a Neo4j Knowledge Graph with Cypher Query Generation.
""")

tab1, tab2, tab3 = st.tabs(["💬 Chat Comparison", "📊 Evaluation Metrics", "⚙️ Architecture & Settings"])

with tab1:
    st.header("Ask a Question")
    st.markdown("Enter a query to see how both systems answer it side-by-side.")
    
    query = st.text_input("Query:", placeholder="What is the primary purpose of the ISO 20022 Payments Guide?")
    
    col1, col2 = st.columns(2)
    
    if st.button("Submit Query"):
        with st.spinner("Processing..."):
            with col1:
                st.subheader("Vector RAG")
                try:
                    vec_pipeline = VectorRAGPipeline()
                    # NOTE: use the pipeline's query() (returns {answer, sources})
                    # — qa_chain.invoke() returns a plain str via StrOutputParser,
                    # so .get("result") on it would crash.
                    vec_result = vec_pipeline.query(query)
                    answer = (vec_result.get("answer") or "").strip()
                    if answer:
                        st.success("Answer Generated")
                        st.write(answer)
                    else:
                        st.warning("Vector RAG returned no answer.")
                    
                    with st.expander("View Retrieved Context"):
                        docs = vec_result.get("sources", [])
                        for i, doc in enumerate(docs):
                            st.markdown(f"**Chunk {i+1}**")
                            st.write(doc.page_content)
                except Exception as e:
                    st.error(f"Vector RAG Error: {e}")
                    if "credits" in str(e).lower() or "402" in str(e):
                        st.warning(
                            "💡 This is a HuggingFace billing/credits error. "
                            "Add HF prepaid credits / PRO, or switch providers to the "
                            "free Groq fallback (llama-3.3-70b-versatile) in config/settings.py."
                        )
            
            with col2:
                st.subheader("Graph RAG")
                try:
                    graph_retriever = GraphRAGRetriever()
                    graph_result = graph_retriever.query(query)
                    if graph_result.get("error"):
                        st.error(f"Graph RAG Error: {graph_result['error']}")
                        if "credits" in str(graph_result["error"]).lower() or "402" in str(graph_result["error"]):
                            st.warning(
                                "💡 This is a HuggingFace billing/credits error. "
                                "Add HF prepaid credits / PRO, or switch providers to the "
                                "free Groq fallback (llama-3.3-70b-versatile) in config/settings.py."
                            )
                    else:
                        answer = (graph_result.get("answer") or "").strip()
                        if answer:
                            st.success("Answer Generated")
                            st.write(answer)
                        else:
                            st.warning("Graph RAG returned no answer.")
                    
                    with st.expander("View Retrieved Context"):
                        ctx = graph_result.get("context", [])
                        if ctx:
                            for i, c in enumerate(ctx):
                                st.markdown(f"**Knowledge {i+1}**")
                                st.write(c)
                        else:
                            st.write("No context retrieved from Graph.")
                except Exception as e:
                    st.error(f"Graph RAG Error: {e}")

with tab2:
    st.header("Evaluation Metrics (Ragas)")
    st.markdown("""
    This section displays the evaluation results generated by `evaluation/evaluator.py`.
    Make sure you have run the evaluator script first to generate the CSV files.
    """)
    
    # Check if CSVs exist
    vec_csv = os.path.join(os.path.dirname(os.path.dirname(__file__)), "evaluation", "vector_rag_metrics.csv")
    graph_csv = os.path.join(os.path.dirname(os.path.dirname(__file__)), "evaluation", "graph_rag_metrics.csv")
    
    vec_metrics = load_metrics_from_csv(vec_csv)
    graph_metrics = load_metrics_from_csv(graph_csv)
    
    if vec_metrics and graph_metrics:
        st.pyplot(create_radar_chart(vec_metrics, graph_metrics))
        
        st.subheader("Raw Metric Averages")
        mcol1, mcol2 = st.columns(2)
        with mcol1:
            st.write("**Vector RAG**")
            st.json(vec_metrics)
        with mcol2:
            st.write("**Graph RAG**")
            st.json(graph_metrics)
    else:
        st.warning("Evaluation metrics not found. Please run `python evaluation/evaluator.py` first.")

with tab3:
    st.header("Architecture")
    st.markdown("""
    ### Vector RAG Pipeline
    1. **Loader**: PyMuPDF Loader
    2. **Chunker**: RecursiveCharacterTextSplitter (1000 chunk size, 200 overlap)
    3. **Embeddings**: `sentence-transformers/all-mpnet-base-v2` (Local HuggingFace)
    4. **Vector Store**: FAISS
    5. **QA Model**: shared answer model (see live config below)

    ### Graph RAG Pipeline
    1. **Extractor Model**: frontier LLM (see live config below)
    2. **Vision Model (for images)**: see live config below
    3. **Graph Store**: Neo4j
    4. **Cypher Generation**: see live config below
    5. **QA Model**: shared answer model (see live config below)
    """)

    # Live config straight from config/settings.py so the app always shows
    # the provider/model actually in use (no stale hardcoded text).
    st.markdown("**Live model/provider config** (from `config/settings.py`):")
    st.code(
        f"Extraction : {settings.EXTRACTION_MODEL}  via {settings.EXTRACTION_PROVIDER}\n"
        f"Refinement : {settings.REFINEMENT_MODEL}  via {settings.REFINEMENT_PROVIDER}\n"
        f"Cypher     : {settings.CYPHER_MODEL}  via {settings.CYPHER_PROVIDER}\n"
        f"Answer QA  : {settings.ANSWER_MODEL}  via {settings.ANSWER_PROVIDER}\n"
        f"Vector LLM : {settings.llm_provider}  ({settings.groq_model})\n"
        f"VLM        : {settings.VLM_MODEL}  via {settings.VLM_PROVIDER}\n"
        f"Embeddings : {settings.embedding_model}  (local)"
    )
