import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

def create_radar_chart(vector_metrics: dict, graph_metrics: dict, save_path: str = None) -> plt.Figure:
    """
    Creates a radar chart comparing Vector RAG and Graph RAG metrics.
    Metrics dicts should contain float values between 0 and 1 for:
    'faithfulness', 'answer_relevancy', 'context_precision', 'context_recall'
    """
    labels = np.array(['Faithfulness', 'Answer Relevancy', 'Context Precision', 'Context Recall'])
    
    # Extract values in order
    def get_vals(metrics_dict):
        return np.array([
            metrics_dict.get('faithfulness', 0.0),
            metrics_dict.get('answer_relevancy', 0.0),
            metrics_dict.get('context_precision', 0.0),
            metrics_dict.get('context_recall', 0.0)
        ])
        
    vec_vals = get_vals(vector_metrics)
    graph_vals = get_vals(graph_metrics)
    
    # Close the polygon for radar chart
    vec_vals = np.concatenate((vec_vals, [vec_vals[0]]))
    graph_vals = np.concatenate((graph_vals, [graph_vals[0]]))
    
    # Calculate angles
    angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)
    angles = np.concatenate((angles, [angles[0]]))
    
    fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))
    
    # Plot Vector RAG
    ax.plot(angles, vec_vals, 'o-', linewidth=2, label='Vector RAG', color='blue')
    ax.fill(angles, vec_vals, alpha=0.25, color='blue')
    
    # Plot Graph RAG
    ax.plot(angles, graph_vals, 'o-', linewidth=2, label='Graph RAG', color='red')
    ax.fill(angles, graph_vals, alpha=0.25, color='red')
    
    # Set labels
    ax.set_thetagrids(angles[:-1] * 180/np.pi, labels)
    
    # Set limits
    ax.set_ylim(0, 1)
    
    plt.legend(loc='upper right', bbox_to_anchor=(1.1, 1.1))
    plt.title('RAG Pipeline Comparison (Ragas Metrics)', y=1.08)
    
    if save_path:
        plt.savefig(save_path, bbox_inches='tight')
        
    return fig

def load_metrics_from_csv(csv_path: str) -> dict:
    """
    Loads metrics from a CSV file generated by evaluation/evaluator.py
    and returns the mean of each metric as a dictionary.
    """
    if not os.path.exists(csv_path):
        return {}
    
    df = pd.read_csv(csv_path)
    means = df.mean(numeric_only=True).to_dict()
    return means
